export enum TableauEvents {
  CUSTOM_MARK_CONTEXT_MENU = 'custommarkcontextmenu',
  CUSTOM_VIEW_LOAD = 'customviewload',
  CUSTOM_VIEW_REMOVE = 'customviewremove',
  CUSTOM_VIEW_SAVE = 'customviewsave',
  CUSTOM_VIEW_SET_DEFAULT = 'customviewsetdefault',
  FILTER_CHANGE = 'filterchange',
  FIRST_INTERACTIVE = 'firstinteractive',
  FIRST_VIZ_SIZE_KNOWN = 'firstvizsizeknown',
  MARKS_SELECTION = 'marksselection',
  MARKS_HIGHLIGHT = 'markshighlight',
  PARAMETER_VALUE_CHANGE = 'parametervaluechange',
  STORY_POINT_SWITCH = 'storypointswitch',
  TAB_SWITCH = 'tabswitch',
  TOOLBAR_STATE_CHANGE = 'toolbarstatechange',
  URL_ACTION = 'urlaction',
  VIZ_RESIZE = 'vizresize',
}
